esphome:
  name: pflanzensensor-sebastian

esp8266:
  board: d1_mini
  # framework:
  #   type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: pflanzensensor-sebastian
    password: !secret api_password

logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

captive_portal:

web_server:
  port: 80

# mqtt:
#   broker: mqtt.curious.bio
#   # discovery: true

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"
    update_interval: 10s
  - platform: adc
    pin: A0
    name: "Bodenfeuchte"
    update_interval: 10s
